export const requestHeaders = [A-IM
  Accept
  Accept-Charset
  Accept-Datetime
  Accept-Encoding
  Accept-Language
  "Access-Control-Request-Method,
  Access-Control-Request-Headers[11]"
  Authorization
  Cache-Control
  Connection
  Content-Encoding
  Content-Length
  Content-MD5
  Content-Type
  Cookie
  Date
  Expect
  Forwarded
  From
  Host
  HTTP2-Settings
  If-Match
  If-Modified-Since
  If-None-Match
  If-Range
  If-Unmodified-Since
  Max-Forwards
  Origin[11]
  Pragma
  Proxy-Authorization
  Range
  Referer [sic]
  TE
  Trailer
  Transfer-Encoding
  User-Agent
  Upgrade
  Via
  Warning]
