export const setupRequests = [
  {
    wholeURI: 'https://disqus.com/api/3.0/forums/create.json',
    endpoint: 'forums/create',
    statusCode: '200',
    httpMethod: 'POST',
    headers: {
      'X-Ratelimit-Remaining': 1000,
      'Access-Control-Expose-Headers': 'Last-Modified',
      'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
      Vary: 'Origin',
      'X-Ratelimit-Limit': 1000,
      'Access-Control-Allow-Credentials': true,
      'Access-Control-Allow-Origin': 'https://disqus.com',
      'Content-Type': 'application/json',
      'X-Ratelimit-Reset': 1585857600,
    },
    body: {
      code: 0,
      response: {
        aetBannerConfirmation: null,
        raw_guidelines: null,
        twitterName: null,
        commentsLinkOne: '1 Comment',
        guidelines: null,
        flagThreshold: 0,
        favicon: {
          permalink: 'https://disqus.com/api/forums/favicons/lnutest.jpg',
          cache: '//a.disquscdn.com/1583455952/images/favicon-default.png',
        },
        commentsLinkZero: '0 Comments',
        disableDisqusBranding: false,
        id: 'lnutest',
        createdAt: '2020-04-02T15:15:33.870618',
        category: null,
        aetBannerEnabled: false,
        aetBannerTitle: null,
        founder: '270513023',
        colorScheme: 'auto',
        daysAlive: 0,
        commentsLinkMultiple: '{num} Comments',
        installCompleted: false,
        newPolicy: true,
        commentPolicyText: null,
        permissions: {},
        channel: null,
        sort: 4,
        description: null,
        moderatorBadgeText: '',
        raw_description: null,
        adsReviewStatus: 0,
        pk: '6041115',
        forumCategory: null,
        aetEnabled: false,
        commentPolicyLink: null,
        aetBannerDescription: null,
        name: 'lnu+test',
        language: 'en',
        settings: {
          threadRatingsEnabled: false,
          adsDRNativeEnabled: true,
          behindClickEnabled: false,
          disable3rdPartyTrackers: false,
          adsVideoEnabled: true,
          adsProductVideoEnabled: true,
          adsPositionTopEnabled: true,
          audienceSyncEnabled: false,
          unapproveLinks: false,
          adsEnabled: true,
          adsProductLinksThumbnailsEnabled: true,
          hasCustomAvatar: false,
          organicDiscoveryEnabled: false,
          adsProductDisplayEnabled: false,
          discoveryLocked: false,
          threadReactionsEnabled: false,
          linkAffiliationEnabled: true,
          disableSocialShare: false,
          allowAnonPost: false,
          adsProductStoriesEnabled: true,
          adultContent: false,
          allowAnonVotes: false,
          gifPickerEnabled: true,
          mustVerify: true,
          mustVerifyEmail: true,
          flaggingNotifications: false,
          ssoRequired: false,
          mediaembedEnabled: true,
          adsPositionBottomEnabled: true,
          adsProductLinksEnabled: true,
          validateAllPosts: false,
          flaggingEnabled: false,
          adsSettingsLocked: false,
          isVIP: false,
          adsPositionInthreadEnabled: true,
        },
        organizationId: 4006545,
        typeface: 'auto',
        url: null,
        daysThreadAlive: 0,
        avatar: {
          small: {
            permalink:
              'https://disqus.com/api/forums/avatars/lnutest.jpg?size=32',
            cache: '//a.disquscdn.com/1583455952/images/noavatar32.png',
          },
          large: {
            permalink:
              'https://disqus.com/api/forums/avatars/lnutest.jpg?size=92',
            cache: '//a.disquscdn.com/1583455952/images/noavatar92.png',
          },
        },
        signedUrl: null,
      },
    },
  },
  {
    wholeURI: 'https://disqus.com/api/3.0/threads/create.json',
    endpoint: 'threads/create',
    statusCode: '200',
    httpMethod: 'POST',
    headers: {
      'X-Ratelimit-Remaining': 995,
      'Access-Control-Expose-Headers': 'Last-Modified',
      'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
      Vary: 'Origin',
      'X-Ratelimit-Limit': 1000,
      'Access-Control-Allow-Credentials': true,
      'Content-Type': 'application/json',
      'X-Ratelimit-Reset': 1586188800,
    },
    body: {
      code: 0,
      response: {
        feed: 'https://lnutest.disqus.com/lnutest/latest.rss',
        clean_title: 'lnutest',
        dislikes: 0,
        likes: 0,
        message: null,
        ratingsEnabled: false,
        id: '7954170327',
        createdAt: '2020-04-06T15:52:02',
        category: '8259415',
        author: '270513023',
        media: [],
        userScore: 0,
        isSpam: false,
        signedLink: 'https://disqus.com/home/discussion/lnutest/lnutest/',
        isDeleted: false,
        hasStreaming: false,
        raw_message: null,
        isClosed: false,
        link: 'https://disqus.com/home/discussion/lnutest/lnutest/',
        slug: 'lnutest',
        forum: 'lnutest',
        identifiers: [],
        posts: 0,
        userSubscription: false,
        validateAllPosts: false,
        title: 'lnutest',
        ipAddress: '83.248.27.139',
        highlightedPost: null,
      },
    },
  },
  {
    wholeURI: 'https://disqus.com/api/3.0/categories/create.json',
    endpoint: 'threads/create',
    statusCode: '200',
    httpMethod: 'POST',
    headers: {
      'X-Ratelimit-Remaining': 995,
      'Access-Control-Expose-Headers': 'Last-Modified',
      'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
      Vary: 'Origin',
      'X-Ratelimit-Limit': 1000,
      'Access-Control-Allow-Credentials': true,
      'Content-Type': 'application/json',
      'X-Ratelimit-Reset': 1586188800,
    },
    body: {
      code: 0,
      response: {
        isDefault: false,
        title: 'news',
        id: '8268142',
        forum: 'lnutest',
        order: 0,
      },
    },
  },
]
