export const setupRequests = [
  {
    wholeURI: 'https://disqus.com/api/3.0/forums/create.json',
    endpoint: 'forums/create',
    statusCode: '200',
    httpMethod: 'POST',
    headers: {
      'X-Ratelimit-Remaining': 1000,
      'Access-Control-Expose-Headers': 'Last-Modified',
      'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
      Vary: 'Origin',
      'X-Ratelimit-Limit': 1000,
      'Access-Control-Allow-Credentials': true,
      'Access-Control-Allow-Origin': 'https://disqus.com',
      'Content-Type': 'application/json',
      'X-Ratelimit-Reset': 1585857600,
    },
    body: {
      code: 0,
      response: {
        aetBannerConfirmation: null,
        raw_guidelines: null,
        twitterName: null,
        commentsLinkOne: '1 Comment',
        guidelines: null,
        flagThreshold: 0,
        favicon: {
          permalink: 'https://disqus.com/api/forums/favicons/lnutest.jpg',
          cache: '//a.disquscdn.com/1583455952/images/favicon-default.png',
        },
        commentsLinkZero: '0 Comments',
        disableDisqusBranding: false,
        id: 'lnutest',
        createdAt: '2020-04-02T15:15:33.870618',
        category: null,
        aetBannerEnabled: false,
        aetBannerTitle: null,
        founder: '270513023',
        colorScheme: 'auto',
        daysAlive: 0,
        commentsLinkMultiple: '{num} Comments',
        installCompleted: false,
        newPolicy: true,
        commentPolicyText: null,
        permissions: {},
        channel: null,
        sort: 4,
        description: null,
        moderatorBadgeText: '',
        raw_description: null,
        adsReviewStatus: 0,
        pk: '6041115',
        forumCategory: null,
        aetEnabled: false,
        commentPolicyLink: null,
        aetBannerDescription: null,
        name: 'lnu+test',
        language: 'en',
        settings: {
          threadRatingsEnabled: false,
          adsDRNativeEnabled: true,
          behindClickEnabled: false,
          disable3rdPartyTrackers: false,
          adsVideoEnabled: true,
          adsProductVideoEnabled: true,
          adsPositionTopEnabled: true,
          audienceSyncEnabled: false,
          unapproveLinks: false,
          adsEnabled: true,
          adsProductLinksThumbnailsEnabled: true,
          hasCustomAvatar: false,
          organicDiscoveryEnabled: false,
          adsProductDisplayEnabled: false,
          discoveryLocked: false,
          threadReactionsEnabled: false,
          linkAffiliationEnabled: true,
          disableSocialShare: false,
          allowAnonPost: false,
          adsProductStoriesEnabled: true,
          adultContent: false,
          allowAnonVotes: false,
          gifPickerEnabled: true,
          mustVerify: true,
          mustVerifyEmail: true,
          flaggingNotifications: false,
          ssoRequired: false,
          mediaembedEnabled: true,
          adsPositionBottomEnabled: true,
          adsProductLinksEnabled: true,
          validateAllPosts: false,
          flaggingEnabled: false,
          adsSettingsLocked: false,
          isVIP: false,
          adsPositionInthreadEnabled: true,
        },
        organizationId: 4006545,
        typeface: 'auto',
        url: null,
        daysThreadAlive: 0,
        avatar: {
          small: {
            permalink:
              'https://disqus.com/api/forums/avatars/lnutest.jpg?size=32',
            cache: '//a.disquscdn.com/1583455952/images/noavatar32.png',
          },
          large: {
            permalink:
              'https://disqus.com/api/forums/avatars/lnutest.jpg?size=92',
            cache: '//a.disquscdn.com/1583455952/images/noavatar92.png',
          },
        },
        signedUrl: null,
      },
    },
  },
  {
    wholeURI: 'https://disqus.com/api/3.0/threads/create.json',
    endpoint: 'threads/create',
    statusCode: '200',
    httpMethod: 'POST',
    headers: {
      'X-Ratelimit-Remaining': 995,
      'Access-Control-Expose-Headers': 'Last-Modified',
      'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
      Vary: 'Origin',
      'X-Ratelimit-Limit': 1000,
      'Access-Control-Allow-Credentials': true,
      'Content-Type': 'application/json',
      'X-Ratelimit-Reset': 1586188800,
    },
    body: {
      code: 0,
      response: {
        feed: 'https://lnutest.disqus.com/lnutest/latest.rss',
        clean_title: 'lnutest',
        dislikes: 0,
        likes: 0,
        message: null,
        ratingsEnabled: false,
        id: '7954170327',
        createdAt: '2020-04-06T15:52:02',
        category: '8259415',
        author: '270513023',
        media: [],
        userScore: 0,
        isSpam: false,
        signedLink: 'https://disqus.com/home/discussion/lnutest/lnutest/',
        isDeleted: false,
        hasStreaming: false,
        raw_message: null,
        isClosed: false,
        link: 'https://disqus.com/home/discussion/lnutest/lnutest/',
        slug: 'lnutest',
        forum: 'lnutest',
        identifiers: [],
        posts: 0,
        userSubscription: false,
        validateAllPosts: false,
        title: 'lnutest',
        ipAddress: '83.248.27.139',
        highlightedPost: null,
      },
    },
  },
  {
    wholeURI: 'https://disqus.com/api/3.0/categories/create.json',
    endpoint: 'categories/create',
    statusCode: '200',
    httpMethod: 'POST',
    headers: {
      'X-Ratelimit-Remaining': 995,
      'Access-Control-Expose-Headers': 'Last-Modified',
      'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
      Vary: 'Origin',
      'X-Ratelimit-Limit': 1000,
      'Access-Control-Allow-Credentials': true,
      'Content-Type': 'application/json',
      'X-Ratelimit-Reset': 1586188800,
    },
    body: {
      code: 0,
      response: {
        isDefault: false,
        title: 'news',
        id: '8268142',
        forum: 'lnutest',
        order: 0,
      },
    },
  },
  {
    wholeURI: 'https://disqus.com/api/3.0/posts/create.json',
    endpoint: 'threads/create',
    statusCode: '200',
    httpMethod: 'POST',
    headers: {
      'X-Ratelimit-Remaining': 995,
      'Access-Control-Expose-Headers': 'Last-Modified',
      'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
      Vary: 'Origin',
      'X-Ratelimit-Limit': 1000,
      'Access-Control-Allow-Credentials': true,
      'Content-Type': 'application/json',
      'X-Ratelimit-Reset': 1586188800,
    },
    body: {
      code: 0,
      response: {
        editableUntil: '2020-04-15T09:10:27',
        dislikes: 0,
        numReports: 0,
        likes: 0,
        message: '<p>7954170327</p>',
        isSpam: false,
        isHighlighted: false,
        author: {
          isFollowing: false,
          disable3rdPartyTrackers: false,
          isPowerContributor: false,
          isFollowedBy: false,
          homeOnboardingComplete: false,
          isPrimary: true,
          id: '270513023',
          flaggedForSpamReview: false,
          emailHash: '65bf55fb2cbcdb17c6496e2169461907',
          anonymizedIdentifier:
            'd1788aac3b8c2d1d68520d2cd112fa9e38922114e2299feba2e65ad24ff7f17d599e6e5478bfff27363c5543121154980fc56a66b49c2e47f297c0846205af1b',
          location: '',
          isPrivate: false,
          joinedAt: '2017-11-07T14:14:04',
          email: 'j********@gmail.com',
          isVerified: true,
          username: 'jesper_h_gglund',
          termsAcceptDate: '2019-07-07T19:28:00',
          homeFeedOnboardingComplete: true,
          about: '',
          name: 'Jesper H\u00e4gglund',
          url: '',
          profileUrl: 'https://disqus.com/by/jesper_h_gglund/',
          hasAcceptedGdprTerms: true,
          avatar: {
            small: {
              permalink:
                'https://disqus.com/api/users/avatars/jesper_h_gglund.jpg',
              cache: '//a.disquscdn.com/1585858405/images/noavatar32.png',
            },
            isCustom: false,
            permalink:
              'https://disqus.com/api/users/avatars/jesper_h_gglund.jpg',
            cache: '//a.disquscdn.com/1585858405/images/noavatar92.png',
            large: {
              permalink:
                'https://disqus.com/api/users/avatars/jesper_h_gglund.jpg',
              cache: '//a.disquscdn.com/1585858405/images/noavatar92.png',
            },
          },
          signedUrl: '',
          isAnonymous: false,
        },
        media: [],
        userScore: 0,
        id: '4865776486',
        isDeletedByAuthor: false,
        isDeleted: false,
        parent: null,
        isApproved: true,
        isFlagged: false,
        raw_message: '7954170327',
        isAtFlagLimit: false,
        canVote: true,
        forum: 'lnutest',
        thread: '7954170327',
        approxLoc: {
          lat: 57.70719909667969,
          lng: 11.96679973602295,
        },
        createdAt: '2020-04-08T09:10:27',
        points: 0,
        flags: 0,
        moderationLabels: [],
        isEdited: false,
        sb: false,
        ipAddress: '***.***.***.139',
      },
    },
  },
]
